/** @type {import('tailwindcss').Config} */
// Tema visual do WorkAnt (Material 3, âmbar/dourado industrial)
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#fcf9f8',
        'surface-bright': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#504532',
        'background': '#fcf9f8',
        'on-background': '#1c1b1b',
        'primary': '#795900',
        'on-primary': '#ffffff',
        'primary-container': '#ffbf00',
        'on-primary-container': '#6d5000',
        'primary-fixed': '#ffdfa0',
        'primary-fixed-dim': '#fbbc00',
        'on-primary-fixed': '#261a00',
        'on-primary-fixed-variant': '#5c4300',
        'secondary': '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e4e2e1',
        'on-secondary-container': '#656464',
        'tertiary': '#904d00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffbb85',
        'on-tertiary-container': '#824400',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'outline': '#827660',
        'outline-variant': '#d4c5ab',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'inverse-primary': '#fbbc00',
        'surface-tint': '#795900',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
