/** @type {import('tailwindcss').Config} */
// Tema visual do WorkAnt — cores derivadas do logo:
// verde #00c544 (formiga) · ink #09151e (traço) · ciano #09f0f6 (LEDs)
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#f9fbfa',
        'surface-bright': '#f9fbfa',
        'surface-dim': '#d9dedb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f6f4',
        'surface-container': '#ecf1ee',
        'surface-container-high': '#e6ebe8',
        'surface-container-highest': '#e0e5e2',
        'surface-variant': '#e0e5e2',
        'on-surface': '#09151e',
        'on-surface-variant': '#3c464d',
        'background': '#f9fbfa',
        'on-background': '#09151e',
        'primary': '#008f3c',
        'on-primary': '#ffffff',
        'primary-container': '#00c544',
        'on-primary-container': '#04260f',
        'primary-fixed': '#a9f5bc',
        'primary-fixed-dim': '#00c544',
        'on-primary-fixed': '#04260f',
        'on-primary-fixed-variant': '#006d2e',
        'secondary': '#5c666d',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0e5e2',
        'on-secondary-container': '#414b52',
        'tertiary': '#0891a6',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#9ef4fa',
        'on-tertiary-container': '#00363e',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'outline': '#6b7680',
        'outline-variant': '#c6d0d6',
        'inverse-surface': '#1c2830',
        'inverse-on-surface': '#eef2f0',
        'inverse-primary': '#00c544',
        'surface-tint': '#008f3c',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
