version: '3'

services:    
  db:
    container_name: postdb
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=data_db
    volumes:
      - ../db:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: appw
    build:
      context: ..
      dockerfile: docker/dockerfile
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - ../uploads:/usr/aplication/uploads
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
