version: '3'

services:    
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=data_db
    volumes:
      - ../db:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: docker/dockerfile
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - ../uploads:/uploads
    depends_on:
      - db
